spring.application.name=myreport-backend
server.port=8080

spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/myreport_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET:MyReportJwtSecretKeyThatShouldBeChangedInProduction1234567890}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
app.jwt.remember-expiration-ms=${JWT_REMEMBER_EXPIRATION_MS:604800000}
app.super-admin.email=${SUPER_ADMIN_EMAIL:ankitapatil00001@gmail.com}
app.super-admin.password=${SUPER_ADMIN_PASSWORD:Ankita@12345}
app.frontend-origin=${FRONTEND_ORIGIN:http://localhost:3000}

razorpay.key-id=${RAZORPAY_KEY_ID:}
razorpay.key-secret=${RAZORPAY_KEY_SECRET:}
