name: Deploy MyReport

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd ~/My-report

            git pull origin main

            # Frontend
            cd client
            npm install
            rm -rf .next .next-build
            npm run build
            pm2 restart myreport-client

            # Backend
            cd ../server
            mvn clean package -DskipTests
            pm2 restart myreport-server
